#include <types.h>
#include <default_args.h>
#include <menc_assert.h>
#include <utils.h>
#include <data_structures.h>
#include <memory_utils.h>
#include <menc_string.h>
#include <memory_managment.h>
#include <logger.h>
#include <menc_string.c>
#include <menc_math.h>
#include <logger.c>
#include <virtual_mem_allocator.h>
#include <memory_managment.c>
#include <data_structures.c>
